### ISSUE TITLE
SSR and styled-components

### ISSUE THREAD

**Issue by heban** [antonybudianto/cra-universal#100]
Hi @antonybudianto !

First of all, thanks for `cra-universal`, it's just amazing thing. 
Few days ago I started to create simple React app by ejecting from create-react-app (I just wanted to add some extra linters to basic configuration). Next I added cra-universal and I used `cra-universal init` command. I would like to use cra-universal with styled-components and for this scenario I modified `app.js` file like this:

```
import {
  createReactAppExpress,
} from '@cra-express/core';

import { renderToNodeStream } from 'react-dom/server';

const path = require('path');
const React = require('react');
const { ServerStyleSheet } = require('styled-components');
const { default: App } = require('../src/app');

const clientBuildPath = path.resolve(__dirname, '../client');

let AppClass = App;
const sheet = new ServerStyleSheet();
const jsx = sheet.collectStyles(<AppClass />);

const app = createReactAppExpress({
  clientBuildPath,
  universalRender: () => sheet.interleaveWithNodeStream(renderToNodeStream(jsx)),
});

if (module.hot) {
  module.hot.accept('../src/app', () => {
    const { default: App } = require('../src/app');
    AppClass = App;
    console.log('✅ Server hot reloaded App');
  });
}

module.exports = app;
```

Styles work as a charm, but in console I have an error:
`Warning: Prop `className` did not match. Server: "sc-bdVaJa jQKJuy" Client: "header__HeaderWrapper-sc-1ya4j2f-0 ddZyIi"`

Where is my mistake? I use hydrate in index.js and in my package.json I have this babel configuration:
```
"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      ["babel-plugin-styled-components", {
        "ssr": true
      }]
    ]
  }
```

Greetings

**Comment by antonybudianto** [comment]
Hi,

I never used styled-component before, so cannot help much :(
You may want to post your issue on Stackoverflow instead for better assistance.

**Comment by antonybudianto** [comment]
Btw, do you have `server/.babelrc` file? Just wanna make sure you had included the plugin (babel-plugin-styled-components) here

**Comment by heban** [comment]
Ok that was my mistake ;) I mixed import statements with require. With your suggestion with creating .babelrc everything works without errors! :D That's amazing! Thank You one more time :)

**Comment by antonybudianto** [comment]
Glad it worked 👍
