### ISSUE TITLE
This browser doesn't support requestAnimationFrame

### ISSUE THREAD

**Issue by hoantran-it** [antonybudianto/cra-universal#101]
I'm migrating my project from csr to ssr and facing up many problem due to project complexity. Have you ever seen this type of error?

![image](https://user-images.githubusercontent.com/13161875/45930910-172fbb00-bf90-11e8-8fd6-e02f040b7069.png)

**Comment by antonybudianto** [comment]
please read this
https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by hoantran-it** [comment]
I tried but it can not solve the problem. This error occur when building ssr. In csr it works normally :(

**Comment by antonybudianto** [comment]
I think the error comes from the 3rd party library you used, `node_modules/schedule`

**Comment by hoantran-it** [comment]
I checked but I think the problem is not come from that because csr work normally. Do we have to do something when using redux store? I tried with your wiki instruction :(

**Comment by antonybudianto** [comment]
Yes I know that your CSR works, but I mean the library might not support SSR.
 When you decided to use SSR, you must make sure all your library supports SSR too

**Comment by antonybudianto** [comment]
Since your project complexity seems high, I advise you try to migrate at slow pace, move the code little by little so you didn't get much error at the beginning. Best luck.

**Comment by hoantran-it** [comment]
Thank you! I will try.
