### ISSUE TITLE
Feature to ignore ssr for some component (file)

### ISSUE THREAD

**Issue by hoantran-it** [antonybudianto/cra-universal#102]
Just a suggestion to make cra-universal become more robustness. In some case, we can exclude some  component (file) from ssr. Something like this one https://github.com/kadirahq/react-no-ssr

To be honest I think with a real project we have to add many third party lib and may be most of them support csr only. It will be a limitation. Wdyt?

**Comment by antonybudianto** [comment]
There's no way to exclude the file from bundling, the best way to ignore component from being server-rendered is to mount them after componentDidMount phase.

**Comment by antonybudianto** [comment]
But if you have a PR, I might take look and will review it

**Comment by hoantran-it** [comment]
Thanks for your explanation! Have you check that cra-universal can work well with redux and any example available? I try but it produce some odd error even just small amount of code

**Comment by hoantran-it** [comment]
Ok take your time. I will try. Thanks!
