### ISSUE TITLE
Getting error while installing and running with command "npx cra-universal start" ?

### ISSUE THREAD

**Issue by Trilochan20** [antonybudianto/cra-universal#104]
Hi, there. 
Read your article [here](https://medium.com/@antonybudianto/new-cra-universal-3-0-0-released-37ceb19d31fb). It's really awesome. So I've a existing project I was working with react, react context-api, firebase. I installed using these 
`# Install new cra-universal
$ npm install -D cra-universal`

I got this in terminal 
`npm install -D cra-universal
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN file-loader@1.1.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@2.29.0 requires a peer of webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3 but none is installed. You must install peer dependencies yourself.
npm WARN sw-precache-webpack-plugin@0.11.4 requires a peer of webpack@^1 || ^2 || ^2.1.0-beta || ^2.2.0-beta || ^3 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@2.9.4 requires a peer of webpack@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-manifest-plugin@1.3.2 requires a peer of webpack@1 || 2 || 3 but none is installed. You must install peer dependencies yourself.
npm WARN @cra-express/static-loader@2.2.4 requires a peer of express@4.16.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ cra-universal@3.2.5
removed 948 packages, updated 1 package and audited 36367 packages in 31.14s
found 0 vulnerabilities`
Can I ignore those warnings ? 
When I start with 
`npx cra-universal start`
I get this 
`[ '/home/trilochan/Desktop/ssr_test/src/App.js\nModule build failed (from /home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/babel-loader/lib/index.js):\nSyntaxError: Unexpected token (293:8)\n\n\u001b[0m \u001b[90m 291 | \u001b[39m\n \u001b[90m 292 | \u001b[39m\u001b[36mclass\u001b[39m \u001b[33mApp\u001b[39m \u001b[36mextends\u001b[39m \u001b[33mComponent\u001b[39m {\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 293 | \u001b[39m  state \u001b[33m=\u001b[39m {\n \u001b[90m     | \u001b[39m        \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 294 | \u001b[39m    loading\u001b[33m:\u001b[39m \u001b[36mtrue\u001b[39m\u001b[33m,\u001b[39m\n \u001b[90m 295 | \u001b[39m    cart\u001b[33m:\u001b[39m[]\u001b[33m,\u001b[39m\n \u001b[90m 296 | \u001b[39m    user\u001b[33m:\u001b[39m[]\u001b[33m,\u001b[39m\u001b[0m\n\nBabelLoaderError: SyntaxError: Unexpected token (293:8)\n\n\u001b[0m \u001b[90m 291 | \u001b[39m\n \u001b[90m 292 | \u001b[39m\u001b[36mclass\u001b[39m \u001b[33mApp\u001b[39m \u001b[36mextends\u001b[39m \u001b[33mComponent\u001b[39m {\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 293 | \u001b[39m  state \u001b[33m=\u001b[39m {\n \u001b[90m     | \u001b[39m        \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 294 | \u001b[39m    loading\u001b[33m:\u001b[39m \u001b[36mtrue\u001b[39m\u001b[33m,\u001b[39m\n \u001b[90m 295 | \u001b[39m    cart\u001b[33m:\u001b[39m[]\u001b[33m,\u001b[39m\n \u001b[90m 296 | \u001b[39m    user\u001b[33m:\u001b[39m[]\u001b[33m,\u001b[39m\u001b[0m\n\n    at transpile (/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/babel-loader/lib/index.js:65:13)\n    at Object.module.exports (/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/babel-loader/lib/index.js:173:20)\n @ ./server/app.js 9:15-41 24:2-30:4 25:20-46\n @ ./server/index.js\n @ multi ./server/index.js !/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js!/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js' ]
Hash: e176eca7c280a271d565
Version: webpack 4.19.1
Time: 662ms
Built at: 25/09/2018 1:06:26 PM
    Asset      Size  Chunks             Chunk Names
bundle.js  35.5 KiB    main  [emitted]  main
Entrypoint main = bundle.js

ERROR in /home/trilochan/Desktop/ssr_test/src/App.js
Module build failed (from /home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (293:8)

  291 | 
  292 | class App extends Component {
> 293 |   state = {
      |         ^
  294 |     loading: true,
  295 |     cart:[],
  296 |     user:[],

 @ ./server/app.js 9:15-41 24:2-30:4 25:20-46
 @ ./server/index.js
 @ multi ./server/index.js !/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js!/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js
webpack:////home/trilochan/Desktop/ssr_test/src/App.js?:1
throw new Error("Module build failed (from /home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/babel-loader/lib/index.js):\nSyntaxError: Unexpected token (293:8)\n\n\u001b[0m \u001b[90m 291 | \u001b[39m\n \u001b[90m 292 | \u001b[39m\u001b[36mclass\u001b[39m \u001b[33mApp\u001b[39m \u001b[36mextends\u001b[39m \u001b[33mComponent\u001b[39m {\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 293 | \u001b[39m  state \u001b[33m=\u001b[39m {\n \u001b[90m     | \u001b[39m        \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 294 | \u001b[39m    loading\u001b[33m:\u001b[39m \u001b[36mtrue\u001b[39m\u001b[33m,\u001b[39m\n \u001b[90m 295 | \u001b[39m    cart\u001b[33m:\u001b[39m[]\u001b[33m,\u001b[39m\n \u001b[90m 296 | \u001b[39m    user\u001b[33m:\u001b[39m[]\u001b[33m,\u001b[39m\u001b[0m\n");
^

Error: Module build failed (from /home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (293:8)

  291 | 
  292 | class App extends Component {
> 293 |   state = {
      |         ^
  294 |     loading: true,
  295 |     cart:[],
  296 |     user:[],

    at eval (webpack:////home/trilochan/Desktop/ssr_test/src/App.js?:1:7)
    at Object.../../../../src/App.js (/home/trilochan/Desktop/ssr_test/server-build/bundle.js:762:1)
    at __webpack_require__ (/home/trilochan/Desktop/ssr_test/server-build/bundle.js:683:30)
    at fn (/home/trilochan/Desktop/ssr_test/server-build/bundle.js:60:20)
    at eval (webpack:///./server/app.js?:9:16)
    at Object../server/app.js (/home/trilochan/Desktop/ssr_test/server-build/bundle.js:785:1)
    at __webpack_require__ (/home/trilochan/Desktop/ssr_test/server-build/bundle.js:683:30)
    at fn (/home/trilochan/Desktop/ssr_test/server-build/bundle.js:60:20)
    at eval (webpack:///./server/index.js?:3:11)
    at Object../server/index.js (/home/trilochan/Desktop/ssr_test/server-build/bundle.js:797:1)
sswp> script exited with code 1
sswp> Script did not load or failed HMR, not restarting`

**Comment by antonybudianto** [comment]
> 293 | state = {
| ^

this syntax is still in proposal stage, so you need the babel plugin

**Comment by antonybudianto** [comment]
If your existing project is too complex, I recommend you to migrate the code piece by piece so the warning/errors won't be too overwhelming.

**Comment by antonybudianto** [comment]
Similar to https://github.com/antonybudianto/cra-universal/issues/97#issuecomment-423574225

**Comment by Trilochan20** [comment]
So, Do I have to add '.babelrc' file inside 'server-build' folder and include the following codes in it ? 
`{
  "presets": ["env", "react"],
  "plugins": ["dynamic-import-node", "transform-object-rest-spread"]
}`

**Comment by Trilochan20** [comment]
That worked. Now I am getting this new error in terminal while running `npx cra-universal start` 
getting this `npm WARN webpack-cli@3.1.1 requires a peer of webpack@^4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}[ './server/app.js\nModule not found: Error: Can\'t resolve \'appbase/src/App\' in \'/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/src/config/server\'\nresolve \'appbase/src/App\' in \'/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/src/config/server\'\n  Parsed request is a module\n  using description file: /home/trilochan/Desktop/ssr_test/node_modules/cra-universal/package.json (relative path: ./src/config/server)\n    aliased with mapping \'appbase\': \'/home/trilochan/Desktop/ssr_test/server\' to \'/home/trilochan/Desktop/ssr_test/server/src/App\'\n      using description file: /home/trilochan/Desktop/ssr_test/node_modules/cra-universal/package.json (relative path: ./src/config/server)\n        using description file: /home/trilochan/Desktop/ssr_test/package.json (relative path: ./server/src/App)\n          no extension\n            /home/trilochan/Desktop/ssr_test/server/src/App doesn\'t exist\n          .js\n            /home/trilochan/Desktop/ssr_test/server/src/App.js doesn\'t exist\n          .jsx\n            /home/trilochan/Desktop/ssr_test/server/src/App.jsx doesn\'t exist\n          as directory\n            /home/trilochan/Desktop/ssr_test/server/src/App doesn\'t exist\n[/home/trilochan/Desktop/ssr_test/server/src/App]\n[/home/trilochan/Desktop/ssr_test/server/src/App.js]\n[/home/trilochan/Desktop/ssr_test/server/src/App.jsx]\n @ ./server/app.js 9:15-41 24:2-30:4 25:20-46\n @ ./server/index.js\n @ multi ./server/index.js !/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js!/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js' ]
[ '/home/trilochan/Desktop/ssr_test/node_modules/express/lib/view.js 79:13-25\nCritical dependency: the request of a dependency is an expression\n    at CommonJsRequireContextDependency.getWarnings (/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)\n    at Compilation.reportDependencyErrorsAndWarnings (/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/webpack/lib/Compilation.js:1327:24)\n    at Compilation.finish (/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/webpack/lib/Compilation.js:1138:9)\n    at hooks.make.callAsync.err (/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/webpack/lib/Compiler.js:539:17)\n    at _err0 (eval at create (/home/trilochan/Desktop/ssr_test/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)\n    at _addModuleChain (/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/webpack/lib/Compilation.js:1066:12)\n    at processModuleDependencies.err (/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/node_modules/webpack/lib/Compilation.js:982:9)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n @ /home/trilochan/Desktop/ssr_test/node_modules/express/lib/application.js\n @ /home/trilochan/Desktop/ssr_test/node_modules/express/lib/express.js\n @ /home/trilochan/Desktop/ssr_test/node_modules/express/index.js\n @ /home/trilochan/Desktop/ssr_test/node_modules/@cra-express/core/lib/app.js\n @ /home/trilochan/Desktop/ssr_test/node_modules/@cra-express/core/lib/index.js\n @ ./server/app.js\n @ ./server/index.js\n @ multi ./server/index.js !/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js!/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js' ]
Hash: f09a629655350afbf060
Version: webpack 4.20.0
Time: 18663ms
Built at: 25/09/2018 5:25:05 PM
    Asset      Size  Chunks             Chunk Names
bundle.js  2.29 MiB    main  [emitted]  main
Entrypoint main = bundle.js

WARNING in /home/trilochan/Desktop/ssr_test/node_modules/express/lib/view.js 79:13-25
Critical dependency: the request of a dependency is an expression
 @ /home/trilochan/Desktop/ssr_test/node_modules/express/lib/application.js
 @ /home/trilochan/Desktop/ssr_test/node_modules/express/lib/express.js
 @ /home/trilochan/Desktop/ssr_test/node_modules/express/index.js
 @ /home/trilochan/Desktop/ssr_test/node_modules/@cra-express/core/lib/app.js
 @ /home/trilochan/Desktop/ssr_test/node_modules/@cra-express/core/lib/index.js
 @ ./server/app.js
 @ ./server/index.js
 @ multi ./server/index.js !/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js!/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js

ERROR in ./server/app.js
Module not found: Error: Can't resolve 'appbase/src/App' in '/home/trilochan/Desktop/ssr_test/node_modules/cra-universal/src/config/server'
 @ ./server/app.js 9:15-41 24:2-30:4 25:20-46
 @ ./server/index.js
 @ multi ./server/index.js !/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js!/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js
webpack:///./server/app.js?:9
var _require = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module 'appbase/src/App'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())),
                                                                                                                                                               ^

Error: Cannot find module 'appbase/src/App'
    at webpackMissingModule (webpack:///./server/app.js?:9:80)
    at eval (webpack:///./server/app.js?:9:170)
    at Object../server/app.js (/home/trilochan/Desktop/ssr_test/server/server-build/bundle.js:3737:1)
    at __webpack_require__ (/home/trilochan/Desktop/ssr_test/server/server-build/bundle.js:683:30)
    at fn (/home/trilochan/Desktop/ssr_test/server/server-build/bundle.js:60:20)
    at eval (webpack:///./server/index.js?:3:11)
    at Object../server/index.js (/home/trilochan/Desktop/ssr_test/server/server-build/bundle.js:3749:1)
    at __webpack_require__ (/home/trilochan/Desktop/ssr_test/server/server-build/bundle.js:683:30)
    at fn (/home/trilochan/Desktop/ssr_test/server/server-build/bundle.js:60:20)
    at eval (webpack:////home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js?multi_./server/index.js_!/home/trilochan/Desktop/ssr_test/node_modules/start-server-webpack-plugin/dist/monitor-loader.js:1:1)
sswp> script exited with code 1
sswp> Script did not load or failed HMR, not restarting
`

**Comment by antonybudianto** [comment]
/ssr_test/server/server-build/bundle.js

server-build should be generated on /ssr_test/server-build

hmm, which directory do you run the `npx cra-universal init` command?

**Comment by Trilochan20** [comment]
This are the server/app.js contents
`const path = require('path');

const React = require('react');
import {
  createReactAppExpress,
  handleUniversalRender
} from '@cra-express/core';

const { default: App } = require('../src/App');
const clientBuildPath = path.resolve(__dirname, '../client');

let AppClass = App;

const app = createReactAppExpress({
  clientBuildPath,
  universalRender: () => handleUniversalRender(<AppClass />)()
});

if (module.hot) {
  module.hot.accept('../src/App', () => {
    const { default: App } = require('../src/App');
    AppClass = App;
    console.log('✅ Server hot reloaded App');
  });
}

module.exports = app;`

**Comment by Trilochan20** [comment]
![screenshot from 2018-09-25 18-19-04](https://user-images.githubusercontent.com/29045013/46015498-0c8c3780-c0f0-11e8-8be8-15f50984aea9.png)
![screenshot from 2018-09-25 18-19-25](https://user-images.githubusercontent.com/29045013/46015499-0c8c3780-c0f0-11e8-8db0-bccb23680a99.png)
![screenshot from 2018-09-25 18-19-37](https://user-images.githubusercontent.com/29045013/46015501-0d24ce00-c0f0-11e8-831f-132a72e737c2.png)

**Comment by antonybudianto** [comment]
Can you create reproducible repository so I can inspect better? 

Also please paste the content of your package.json

**Comment by Trilochan20** [comment]
>package.json `{
  "name": "test_app_react_ssr",
  "version": "0.1.0",
  "private": true,
  "proxy": "http://localhost:3000",
  "dependencies": {
    "@babel/core": "^7.1.0",
    "@cra-express/core": "^2.2.5",
    "ajv": "^6.5.1",
    "antd": "^3.6.3",
    "antd-mobile": "^2.2.0",
    "apparel-sorter": "^0.2.1",
    "axios": "^0.18.0",
    "babel-loader": "^8.0.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react-app": "^3.1.2",
    "body-parser": "^1.18.3",
    "express": "^4.16.2",
    "firebase": "^5.2.0",
    "ignore-styles": "^5.0.1",
    "jquery": "^3.3.1",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "morgan": "^1.9.1",
    "rc-drawer": "^1.7.5",
    "react": "^16.5.2",
    "react-device-detect": "^1.5.9",
    "react-dom": "^16.5.2",
    "react-ga": "^2.5.3",
    "react-image-gallery": "^0.8.9",
    "react-image-lightbox": "^5.0.0",
    "react-images": "^0.5.19",
    "react-loadable": "^5.5.0",
    "react-media": "^1.8.0",
    "react-motion-drawer": "^3.1.0",
    "react-phone-input-2": "^2.6.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "react-slick": "^0.23.1",
    "react-sticky": "^6.0.3",
    "react-toastify": "^4.1.0",
    "semantic-ui-css": "^2.3.3",
    "semantic-ui-react": "^0.82.1",
    "slick-carousel": "^1.8.1",
    "tachyons": "^4.10.0",
    "uuid": "^3.3.2",
    "webpack": "^3.1.0",
    "webpack-cli": "^3.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "babel-preset-env": "^1.7.0",
    "cra-universal": "^3.2.5",
    "react-alice-carousel": "^1.10.3"
  }
}`

**Comment by Trilochan20** [comment]
this is what happens in terminal 
![screenshot from 2018-09-25 18-40-58](https://user-images.githubusercontent.com/29045013/46016494-989f5e80-c0f2-11e8-8db3-7357d49b47a5.png)

**Comment by antonybudianto** [comment]
I see, so the log is showing as expected. No idea so far, need to debug from your project

**Comment by antonybudianto** [comment]
hmm why you have     "webpack": "^3.1.0" ?

**Comment by antonybudianto** [comment]
Sorry, which Node and npm version you use?

**Comment by Trilochan20** [comment]
installed webpack@latest got these warnings 
![screenshot from 2018-09-25 18-47-00](https://user-images.githubusercontent.com/29045013/46016829-72c68980-c0f3-11e8-81c2-214a7cbec8f9.png)
then ran the command 
![screenshot from 2018-09-25 18-47-55](https://user-images.githubusercontent.com/29045013/46016855-8c67d100-c0f3-11e8-8b33-5f7f005bcd5e.png) got the previous error again. 
.babelrc not working :(

**Comment by Trilochan20** [comment]
![screenshot from 2018-09-25 18-49-35](https://user-images.githubusercontent.com/29045013/46016911-c46f1400-c0f3-11e8-8762-1afd41385c40.png)

**Comment by antonybudianto** [comment]
Are you sure you've installed https://babeljs.io/docs/en/babel-plugin-transform-class-properties and put it on babelrc?

**Comment by antonybudianto** [comment]
Please check https://babeljs.io/docs/en/babel-plugin-transform-class-properties#via-babelrc-recommended

Your babelrc is missing the plugin...

**Comment by Trilochan20** [comment]
Should I do this ? 
![screenshot from 2018-09-25 19-01-55](https://user-images.githubusercontent.com/29045013/46017586-7e1ab480-c0f5-11e8-9e60-977d13194e66.png)

**Comment by antonybudianto** [comment]
?? 

```json
{ "presets": ["env", "react"], "plugins": ["dynamic-import-node", "transform-object-rest-spread", "transform-class-properties"] }
```
