### ISSUE TITLE
I need to run bundle.js for localhost

### ISSUE THREAD

**Issue by Yuricoden** [antonybudianto/cra-universal#112]
I running the bundle start via PM2. But on which localhost is the application open?

**Comment by antonybudianto** [comment]
You can check your server/index.js file (if you don't have custom server, it should be 3001)
https://github.com/antonybudianto/cra-universal/blob/master/packages/demo/server/index.js#L3

**Comment by Yuricoden** [comment]
I launch only pm2 start bundle.js . And I have 404 page.

**Comment by antonybudianto** [comment]
No errors on the pm2 log?

**Comment by antonybudianto** [comment]
Can you share the repo?

**Comment by Yuricoden** [comment]
I have private repo on bitbucket.
![2018-10-07 06 16 03](https://user-images.githubusercontent.com/19597527/46577838-8ed20100-c9f8-11e8-8153-9b6b8c43a256.png)

**Comment by antonybudianto** [comment]
sorry cannot help much without repo :( 
I need to see if the issue comes from cra-univ or wrong setup

**Comment by Yuricoden** [comment]
Ok!
![2018-10-07 06 29 19](https://user-images.githubusercontent.com/19597527/46577916-57fcea80-c9fa-11e8-878f-abd8dd5b33b7.png)

**Comment by Yuricoden** [comment]
Yep i launch bundle.js
Maybe i rather the problem was in the path.
![2018-10-07 06 41 00](https://user-images.githubusercontent.com/19597527/46578008-57fdea00-c9fc-11e8-9f7b-26f48effabe7.png)

the client folder must be created in the server folder

**Comment by antonybudianto** [comment]
which cra-universal version do you use? server and client folder should be side-to-side.

**Comment by antonybudianto** [comment]
> im use v4.0.0

It's not released yet, you mean `4.0.0-alpha.2`

**Comment by Yuricoden** [comment]
No im use    "cra-universal": "^3.2.5",

**Comment by antonybudianto** [comment]
Sorry cannot help much from this, need the repo so I can debug

**Comment by antonybudianto** [comment]
From the second screenshot, the client should not be inside server folder, it's probably using old cra-universal (<= v2)

**Comment by antonybudianto** [comment]
```
$ ls 
build           node_modules    public          server-build
dist            package.json    server          src
$ cd dist/
$ ls
client          package.json    server
````

**Comment by antonybudianto** [comment]
Sorry will close this for now, please reopen if you have any reproducible repo

**Comment by pcegarra** [comment]
I think this repo is not working, Im trying to create a production build and I just have this:

`!function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s=0)}([function(e,t,r){var n=r(1);e.exports={plugins:[{plugin:n,options:{lessLoaderOptions:{lessOptions:{modifyVars:{"@primary-color":"#E01C26","@btn-font-weight":700},javascriptEnabled:!0}}}}]}},function(e,t){e.exports=require("craco-less")}])`
