### ISSUE TITLE
How do i call fetch for my setState?

### ISSUE THREAD

**Issue by Yuricoden** [antonybudianto/cra-universal#115]
Hello! I'm user router/prefetcher. How do i call fetch for my setState? Thats my example 
![2018-10-26 01 12 11](https://user-images.githubusercontent.com/19597527/47533392-36d24000-d8bc-11e8-98c1-bf4396c27bad.png)

I'm try call setState in promise but no data is transmitted. I need this state to render.
![2018-10-26 01 15 23](https://user-images.githubusercontent.com/19597527/47533505-a34d3f00-d8bc-11e8-8864-5f02114cce2d.png)

**Comment by antonybudianto** [comment]
Hi, please fill the issue template first :)

**Comment by antonybudianto** [comment]
Also make sure you've followed https://github.com/antonybudianto/cra-universal/tree/master/packages/%40cra-express/router-prefetcher

**Comment by antonybudianto** [comment]
componentDidMount is not called during server render, it's only called on client render, so you won't get any data hydrated from server

**Comment by antonybudianto** [comment]
closing for now as no response in few days, feel free to reopen
