### ISSUE TITLE
No size limit on url-loader

### ISSUE THREAD

**Issue by CruelMoney** [antonybudianto/cra-universal#122]
Currently there is no limit on the url-loader, meaning that all images will be inlined in the served html. This means that the initial payload can become very large. 

I suggest using a limit on 10000, similar to create react app scripts.

But for now I'm just extending the webpack config with the following code in crau.config.js: 

```
module.exports = {
	webpackPlugins: [],
	modifyWebpack: config => ({
		...config,
		module: {
			...config.module,
			rules: [
				...config.module.rules.filter(r => r.loaders !== "url-loader"),
				{
					test: /\.(png|jpe?g|gif|bmp|svg)?$/,
					loaders: "url-loader",
					options: {
						limit: 10000,
						name: "/static/media/[name].[hash:8].[ext]"
					}
				}
			]
		}
	})
};
```

**Comment by antonybudianto** [comment]
Hi @CruelMoney , I'm open for the PR 😄

**Comment by CruelMoney** [comment]
Alright, coming up :)

**Comment by antonybudianto** [comment]
Thanks! @CruelMoney

**Comment by ajchili** [comment]
@antonybudianto do mind if I submit one?

**Comment by antonybudianto** [comment]
@ajchili sure! thanks

**Comment by ajchili** [comment]
@antonybudianto I am not very familiar with webpack configs. Should the limit be implemented [here](https://github.com/antonybudianto/cra-universal/blob/master/packages/cra-universal/src/config/webpack.config.js#L98)?
