### ISSUE TITLE
Github link on cra-universal website does not link to repository

### ISSUE THREAD

**Issue by ajchili** [antonybudianto/cra-universal#132]
The Github link at [antonybudianto.github.io/cra-universal/](https://antonybudianto.github.io/cra-universal/) does not link to [github.com/antonybudianto/cra-universal](https://github.com/antonybudianto/cra-universal/). It instead just links to [github.com](https://github.com).

I am not sure if this is the intended effect. Within the [index file](https://github.com/antonybudianto/cra-universal/blob/master/website/pages/en/index.js#L84) it has the repository URL specified but the [footer](https://github.com/antonybudianto/cra-universal/blob/master/website/core/Footer.js#L72) does not have it specified.

**Comment by antonybudianto** [comment]
It's not intended, I missed that part, thanks for the report, do you want to submit a PR?

**Comment by ajchili** [comment]
Yeah, I can submit a PR for this as well.

**Comment by antonybudianto** [comment]
Great! Thanks for your contribution

**Comment by ajchili** [comment]
Fixed with #133.
