### ISSUE TITLE
Invariant Violation when trying to add react router

### ISSUE THREAD

**Issue by supremeboy18** [antonybudianto/cra-universal#135]
I tried following the guide to connect react router to the app. But when using ReactDomServer.renderToNodeStream it throws the following error:

  throw error;
    ^

Invariant Violation: Objects are not valid as a React child (found: object with keys {_readableState, readable, _events, _eventsCount, _maxListeners, partialRenderer}). If you meant to render a collection of children, use an array inst
ead.

**Comment by antonybudianto** [comment]
The guide on https://github.com/antonybudianto/cra-universal/wiki/Integrate-React-Router right?

Maybe you used latest version and the guide is not updated yet.
This part:
```
function handleUniversalRender(req, res) {
  const context = {};
  const stream = ReactDOMServer.renderToNodeStream(
    <StaticRouter location={req.url} context={context}>
      <App />
    </StaticRouter>
  );

  if (context.url) {
    res.redirect(301, context.url);
    return;
  }

  return stream;
}
```

just change it to:
```
function handleUniversalRender(req, res) {
  const context = {};
  const el = (
    <StaticRouter location={req.url} context={context}>
      <App />
    </StaticRouter>
  );

  if (context.url) {
    res.redirect(301, context.url);
    return;
  }

  return el;
}
```

**Comment by allanpichardo** [comment]
The Integrate React Router guide hasn't been updated yet and still has the old instructions.

**Comment by antonybudianto** [comment]
this one has been updated https://antonybudianto.github.io/cra-universal/docs/integrate-react-router.html
