### ISSUE TITLE
Is TypeScript supported?

### ISSUE THREAD

**Issue by amkherad** [antonybudianto/cra-universal#143]
Does this support typescript? because I can't get cra-universal to work with the project created by `npx create-react-app test --typescript` by following steps from [docs/integrate-typescript.html](https://antonybudianto.github.io/cra-universal/docs/integrate-typescript.html)

`Error: TypeScript emitted no output for /src/App.tsx`

**Comment by antonybudianto** [comment]
Have you tried https://github.com/antonybudianto/cra-universal/wiki/Integrate-TypeScript?

**Comment by amkherad** [comment]
Yes, as I originally said, first I run `npx create-react-app test --typescript` then the steps in that guide but it fails. even if I run `npx create-react-app test` everything works fine, but as soon as I reference a typescript file it fails.

**Comment by antonybudianto** [comment]
I see, FYI the guide is made by community, not me. For now, cra-universal doesn't have dedicated support for TypeScript mode. Sorry :(

**Comment by antonybudianto** [comment]
I'm open for PR though

**Comment by janjachacz** [comment]
Use babel-loader


// crau.config.js
```
const webpackMerge = require("webpack-merge");

const tsConfig = {
  resolve: {
    extensions: [".ts", ".tsx"]
  },
  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        loaders: "babel-loader",
        options: {
          babelrc: false,
          extends: "./node_modules/cra-universal/src/config/server/.babelrc"
        }
      }
    ]
  }
};

module.exports = {
  webpackPlugins: [],
  modifyWebpack: config => webpackMerge(config, tsConfig)
};

```

**Comment by antonybudianto** [comment]
Do you use https://babeljs.io/docs/en/babel-preset-typescript? @janjachacz

**Comment by janjachacz** [comment]
@antonybudianto, yes, it's sub-dependency of `react-scripts` 

react-scripts 2.1.8 --> babel-preset-react-app ^7.0.2 --> @babel/preset-typescript 7.1.0

**Comment by antonybudianto** [comment]
Oh cool, I'll put it on the wiki then, thanks! @janjachacz

**Comment by janjachacz** [comment]
No problem @antonybudianto, awesome project by the way! 👏👏👏

**Comment by antonybudianto** [comment]
Thanks @janjachacz  😄

**Comment by devgeeksclub** [comment]
@janjachacz I did fresh install with typescript and got this error 

```
@ multi ./server/index.js !/Users/amesbahi/Code/allTest/ssr/node_modules/start-server-webpack-plugin/dist/monitor-                                                                                                                    
sswp> Cannot apply update.                                                                                                                                                                                                             
sswp> Error: Module build failed (from /Users/amesbahi/Code/allTest/ssr/node_modules/cra-universal/node_modules/bab                                                                                                                    
SyntaxError: /Users/amesbahi/Code/allTest/ssr/src/App.tsx: Unexpected token (7:9)                                                                                                                                                      
                                                                                                                                                                                                                                       
   5 |                                                                                                                                                                                                                                 
   6 |                                                                                                                                                                                                                                 
>  7 | const App: React.FC = () => {                                                                                                                                                                                                   
     |          ^                                                                                                                                                                                                                      
   8 |   return (                                                                                                                                                                                                                      
   9 |     <div className="App">                                                                                                                                                                                                       
  10 |       <header className="App-header"> 
```

**Comment by viet-nv** [comment]
> @janjachacz I did fresh install with typescript and got this error
> 
> ```
> @ multi ./server/index.js !/Users/amesbahi/Code/allTest/ssr/node_modules/start-server-webpack-plugin/dist/monitor-                                                                                                                    
> sswp> Cannot apply update.                                                                                                                                                                                                             
> sswp> Error: Module build failed (from /Users/amesbahi/Code/allTest/ssr/node_modules/cra-universal/node_modules/bab                                                                                                                    
> SyntaxError: /Users/amesbahi/Code/allTest/ssr/src/App.tsx: Unexpected token (7:9)                                                                                                                                                      
>                                                                                                                                                                                                                                        
>    5 |                                                                                                                                                                                                                                 
>    6 |                                                                                                                                                                                                                                 
> >  7 | const App: React.FC = () => {                                                                                                                                                                                                   
>      |          ^                                                                                                                                                                                                                      
>    8 |   return (                                                                                                                                                                                                                      
>    9 |     <div className="App">                                                                                                                                                                                                       
>   10 |       <header className="App-header"> 
> ```

@devgeeksclub  do you solve that issue? I have same problem :'(

**Comment by altwarg** [comment]
@viet-nv , @devgeeksclub  I've notices that this error appears when you're using anonymous functions.
@antonybudianto, we also cannot use `export type`, enums and other typescript things due to "Support for the experimental syntax 'flow' isn't currently enabled" error.

**Comment by shreddish** [comment]
> Thanks @janjachacz 😄

Following the typescript integration page - when I run `npx cra-universal start` I keep getting an error 

`(node:8278) UnhandledPromiseRejectionWarning: TypeError: webpackMerge is not a function`

I have run `npm install webpack-merge` and its in my node_modules directory... Any idea what could be causing it?

**Comment by shreddish** [comment]
Well still can't build getting all sorts of other errors like `const requires declaration` event though the line in the error shows that its being declared - bunch of other sass errors as well - this is not ready for typescript support unfortunately
