### ISSUE TITLE
Can't load scss

### ISSUE THREAD

**Issue by zhiqiang115** [antonybudianto/cra-universal#144]
ERROR in 
/components/Playlist/Playlist.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @mixin lines($line) {
|     overflow: hidden;
|     text-overflow: ellipsis;

sswp> script exited with code 1
sswp> Script did not load or failed HMR, not restarting

**Comment by antonybudianto** [comment]
Sorry I don't support scss 🙏

**Comment by The-Code-Monkey** [comment]
how do we make this support scss.

**Comment by KareemMamdouh** [comment]
how do we make this support scss?!!! @antonybudianto

**Comment by MindfulMe** [comment]
https://github.com/antonybudianto/cra-universal/issues/192
