### ISSUE TITLE
Import of json in components 

### ISSUE THREAD

**Issue by SvenChristian** [antonybudianto/cra-universal#149]
It's not support yet.- right? Can that be also supported?

**Comment by antonybudianto** [comment]
I'm open for PR to add the missing json-loader 🙏

**Comment by antonybudianto** [comment]
PR merged, will release soon

**Comment by SvenChristian** [comment]
Ok have tried it - put get still the same errors

**Comment by antonybudianto** [comment]
sorry it is not released yet 🙏
