### ISSUE TITLE
Can the app with cra-universal be deployed on Heroku? 

### ISSUE THREAD

**Issue by tuskkk** [antonybudianto/cra-universal#153]
I am trying to deploy my isomorphic create-react-app (with cra-universal) on Heroku, but as a  result I get only static site.

**Comment by antonybudianto** [comment]
I've not deployed to Heroku, but if it supports Nodejs, I think it should be fine
https://devcenter.heroku.com/articles/getting-started-with-nodejs

**Comment by antonybudianto** [comment]
I've used Now.sh since it supports free Nodejs deployment
https://cra-universal.now.sh/
