### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by AcidRaZor** [antonybudianto/cra-universal#157]
**Describe the bug**
Followed the instructions, and receive:

> webpack:///C:/_development/TFS/Web/react-ssrtest/src/store/detail.js?:121
>     regeneratorRuntime.mark(function _callee(state, _ref) {
>     ^
> 
> ReferenceError: regeneratorRuntime is not defined
> 

I'm using the following instead of Redux: https://github.com/storeon/storeon

The line that freaks out is line 62 in their index.js file at the Array.forEach:

```
modules.forEach(function (i) {
    if (i) i(store)
  })

```

createStore's code 

```
var createStore = function (modules) {
  var events = { }
  var state = { }

  var on = function (event, cb) {
    (events[event] || (events[event] = [])).push(cb)

    return function () {
      events[event] = events[event].filter(function (i) {
        return i !== cb
      })
    }
  }

  var dispatch = function (event, data) {
    if (event !== '@dispatch') {
      dispatch('@dispatch', [event, data, events[event]])
    }

    if (events[event]) {
      var changes = { }
      var changed
      events[event].forEach(function (i) {
        var diff = i(state, data)
        if (diff && typeof diff.then !== 'function') {
          changed = Object.assign({ }, state, diff)
          Object.assign(changes, diff)
          state = changed
        }
      })
      if (changed) dispatch('@changed', changes)
    }
  }

  var get = function () {
    return state
  }

  var store = { dispatch: dispatch, get: get, on: on }

  modules.forEach(function (i) {
    if (i) i(store)
  })
  dispatch('@init')

  return store
}

module.exports = createStore
```

**Comment by antonybudianto** [comment]
Hi, can you open the issue on StackOverflow instead? I don't support/maintain storeon library.

**Comment by AcidRaZor** [comment]
Actually. I don't think it's storeon. I'm using async/await in my code when doing my API calls. It appears a polyfill is required for some reason?

**Comment by antonybudianto** [comment]
polyfill should be included on app instead of library (cra-universal)

**Comment by AcidRaZor** [comment]
For now I've just removed async/await.

The CRA Server started up, but whenever I try to visit port 3001 (while client is started on port 3000), I get this: 

Invariant Violation: Browser history needs a DOM

Perhaps some other issue with BrowserRouter that I use. Think it's because of this:

https://stackoverflow.com/questions/43058684/react-router-4-browser-history-needs-a-dom

**Comment by antonybudianto** [comment]
Please read https://antonybudianto.github.io/cra-universal/docs/integrate-react-router.html for react-router integration

**Comment by AcidRaZor** [comment]
Sorry for adding onto this. I created the server/app,js with the function, took my browser router out of App.js for client and wrapped it in index.js

I get "Invariant Violation: You should not use <Route> or withRouter() outside a <Router>" error, so there is clearly something wrong with how I put my react app together.

I'll try something else. Thank you for the help.

**Comment by mixcas** [comment]
I'm having this same issue. I'm using async/await in my `handleUniversalRender()`

> polyfill should be included on app instead of library (cra-universal)

How is this done?
