### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command (Note: Resolved with cross-env)

### ISSUE THREAD

**Issue by dentemple** [antonybudianto/cra-universal#17]
**Issue**:  The server fails to start when running  `npm start` within `./server` 

**Environment**: Windows 10, Git Bash

**Full message**:  `$ npm start`

```bash
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-react-app-server@1.0.0 start: `NODE_ENV=development webpack --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-react-app-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging
output above.
```

**Resolution**:  I installed the `cross-env` package to the `./server` folder, then updated the scripts to reflect it:

```json
"scripts": {
    "start": "cross-env NODE_ENV=development webpack --watch",
    "start:prod": "cross-env NNODE_ENV=production node build/bundle.js",
    "build":
      "cross-env NNODE_ENV=production webpack -p --progress --profile --bail",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

**Recommendation**: Add `cross-env` to the CLI, or utilize an equally valid alternative to running these npm scripts on multiple environments.

Thank you for your work on this project!

**Comment by antonybudianto** [comment]
Hi @dentemple 
Do you want to open the PR for `cross-env` ?

**Comment by dentemple** [comment]
Y'know, I've never actually worked on a CLI before.  

Looking at the project, I'm not sure how I would add it.  I'll have to leave this one to you (or someone else).  Sorry!

**Comment by antonybudianto** [comment]
Oh okay, I'll do it on weekend, thanks for the report

**Comment by armanbabai** [comment]
the equivalent in Windows would be
in package.json file:
`SET NODE_ENV=development & nodemon foo.js`

**Comment by best-lucky1030** [comment]
> the equivalent in Windows would be in package.json file: `SET NODE_ENV=development & nodemon foo.js`

Yes, it works and saved my times.
👍  💯
