### ISSUE TITLE
Build command returns "Error building CRA client" due to the ...\cra-universal\...\yargs directory

### ISSUE THREAD

**Issue by dentemple** [antonybudianto/cra-universal#18]
**Issue**: Unable to use the CLI's build feature

**Full Error**:

```bash
$ cra-universal build
Building CRA client...

C:\Users\denny\AppData\Roaming\npm\node_modules\cra-universal\node_modules\yargs\yargs.js:1100
      else throw err
            ^
Error building CRA client.
```

This occurs on a completely clean install of Create React App and CRA Universal, and after following the README to the letter.

Create React's app's `"react-scripts build"` command works normally.

**Environment**: Windows 10, Git Bash, `node v8.9.1`

I assume that this is an issue with using cra-universal on my environment; however, I'm not sure what steps can be taken to resolve this.

**Comment by antonybudianto** [comment]
It's hard for me to debug this one because I didn't use Windows OS. Let's leave this open for now

**Comment by antonybudianto** [comment]
can you update the CLI and recheck? @dentemple

**Comment by antonybudianto** [comment]
closing now, please retry the latest cli and reopen if still happens
