### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by mlshv** [antonybudianto/cra-universal#184]
I think CONTRIBUTING.md will be very helpful for new contributors. 

For example, it was not obvious for me how to run dev build of the library. Also, there are a lot of npm scripts in package.json and README doesn't describe them. The fact that I didn't use lerna before made it even harder to realize.

I could work on it, but I definitely would need some help from more experienced contributors. What do you think?

**Comment by antonybudianto** [comment]
Sure, I can help you along with it!

**Comment by antonybudianto** [comment]
I think for starters, dev should be able to start CRA client+server locally, hence I created the script here https://github.com/antonybudianto/cra-universal/blob/master/package.json#L22

**Comment by antonybudianto** [comment]
also good to know for contributors:
- since we need a way to test the cra-universal locally and seamlessly, we have one CRA app as one of the package so that we can try the cli locally, think of it as the playground for us since it's not actually going to be published.

**Comment by mlshv** [comment]
> I think for starters, dev should be able to start CRA client+server locally, hence I created the script here https://github.com/antonybudianto/cra-universal/blob/master/package.json#L22

There is a problem with react-scripts. It says that webpack versions are incompatible. It requires 4.40.2, but ^4.39.3 is specified in `packages/cra-unversal/package.json`. I managed to fix it by installing 4.40.2. Maybe there is a way to sync versions automatically?
