### ISSUE TITLE
Extra routes

### ISSUE THREAD

**Issue by CruelMoney** [antonybudianto/cra-universal#20]
Was thinking if you could add support for adding express routes? 
Maybe just by allowing passing an existing express instance to `createReactAppExpress`.

Thanks for this great tool!

**Comment by antonybudianto** [comment]
Can you add the routes on this file?
https://github.com/antonybudianto/cra-universal/blob/master/templates/server/src/index.js

**Comment by CruelMoney** [comment]
Tried, but I think that the routing in create-react-app-express takes precedence over any other route.

**Comment by antonybudianto** [comment]
I see, then something needs to be done on the middleware level. I'll check it out on weekend.

**Comment by antonybudianto** [comment]
@CruelMoney hi, can you try this upcoming major release?
https://github.com/antonybudianto/create-react-app-express/tree/dev-lerna#public-exports

It should support passing your express app instance

**Comment by CruelMoney** [comment]
Works beautifully! Thank you.
