### ISSUE TITLE
Does it work with Typescript ?

### ISSUE THREAD

**Issue by olup** [antonybudianto/cra-universal#203]
Cra-universal launches an error on start: cannot find App file in src. Is that because I run a typescript project?

**Comment by ajchili** [comment]
Hey @olup there is support for it, but since it was introduced by a community member it may require some messing around to get it working for your use case. Documentation about it can be found [here](https://github.com/antonybudianto/cra-universal/wiki/Integrate-TypeScript).

**Comment by antonybudianto** [comment]
Coming soon!
https://github.com/antonybudianto/cra-universal/pull/209

**Comment by antonybudianto** [comment]
Please update cra-universal to `4.5.0` for TypeScript support 👍
