### ISSUE TITLE
Add support of inlined SVGs from Create React App (SVGR)

### ISSUE THREAD

**Issue by dmitry-zaets** [antonybudianto/cra-universal#204]
Is it possible to add support of `CRA` build-in feature for SVGs in custom code or it requires changes to `cra-universal`, as the inlined SVG images are missing during the SSR?

It's basically a part of the webpack configuration (adding a plugin for jsx files) from here: 
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L425-L445

CRA documentation: https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

If the PR is needed to support that feature - I'll be glad to make it.

**Comment by antonybudianto** [comment]
Hi, PR is welcome! Later we can check if it works with SSR or not
