### ISSUE TITLE
Use cra-universal on production? Post it here!

### ISSUE THREAD

**Issue by antonybudianto** [antonybudianto/cra-universal#21]
Do you use cra-universal and finally make it to production? Please post your work here! ⭐️ 

> Please **DON'T post issues** here, this one is for testimonials

**Comment by knsakib** [comment]
cra-universal build
Building CRA client...

\cra-universal\node_modules\yargs\yargs.js:1100
      else throw err
           ^
Error building CRA client.

**Comment by antonybudianto** [comment]
@knsakib please post as new issue

**Comment by knsakib** [comment]
it was a problem with the windows. linux is fine. so no worries. :)

**Comment by rigobertoGomez** [comment]
I have this problem, how can fixed?

Connected to CRA Client dev server
CRA Server listening on port 3001!
connect ECONNREFUSED 127.0.0.1:3000

**Comment by rigobertoGomez** [comment]
How can load statics files like a logo of example in create-react-app
beacuse I have this problem!

Warning: Prop `src` did not match. Server: "[object Object]" Client: "/static/media/logo.5d5d9eef.svg"

**Comment by antonybudianto** [comment]
Please create new issues for these, @rigobertoGomez.
