### ISSUE TITLE
Modifying  HTML response from express

### ISSUE THREAD

**Issue by Fransferdy** [antonybudianto/cra-universal#222]
First of all, AWESOME project, thank you for bringing this up.

Second I just finished setting up the basics to use this with a project that was already mid sized, but now I wanted to be able to change the <head> section of the html document, to add tags, title, description, etc, SEO stuff in general, but I am unable to see a way of doing this with cra-universal.

I read the docs and didn`t find anything similar, is there a way a could do this. (modify the rest of the html output from express)

Thanks! This project is a life saver!!

**Comment by antonybudianto** [comment]
Hi, you can custom the server side code like this:
https://github.com/antonybudianto/cra-universal/blob/master/packages/demo/server/app.js#L30
