### ISSUE TITLE
Error: Couldn't find preset "react-app" relative to directory

### ISSUE THREAD

**Issue by reyou** [antonybudianto/cra-universal#24]
I came here from blog post: https://medium.com/@antonybudianto/server-side-rendering-with-react-and-firebase-functions-cd67fdb2b605 

I followed instructions below;

> Install global CLI
> npm install -g cra-universal
> 
> Change dir to your app and init CRA server
> cd ./my-create-react-app
> cra-universal init
> 
> Install server dependencies
> cd ./server
> npm install

and when I run `npm start ` I am getting following error;

`Module build failed: Error: Couldn't find preset "react-app" relative to directory "D:\\app-Server-side-rendering\\server\\src"`

Also `D:\app-Server-side-rendering\src\index.js` page is like below;

![image](https://user-images.githubusercontent.com/6571483/35081667-6452dba4-fbe3-11e7-9327-f7a59d4503cf.png)

And there is not such code like below;

```
// before
ReactDOM.render(...)

// after
ReactDOM.hydrate(...)

```

Can you please suggest?

**Comment by antonybudianto** [comment]
src/index.js is from create-react-app, not from cra-universal
