### ISSUE TITLE
After production built nothing appears in the page source

### ISSUE THREAD

**Issue by knsakib** [antonybudianto/cra-universal#25]
After production built nothing appears in the page source. 

But running client and server works fine. So, wondering does the production built address the SEO?

**Comment by antonybudianto** [comment]
viewing page source is now tricky thanks to Service worker :)
You can use curl to check it, or do hard refresh (Ctrl + Shift + R) on Chrome

**Comment by antonybudianto** [comment]
https://cra-universal.now.sh/ for demo with no service worker, you can check the page source directly

**Comment by knsakib** [comment]
Yes. you are right. Perfect! Awesome :)
