### ISSUE TITLE
React-router will not work I guess, right?

### ISSUE THREAD

**Issue by knsakib** [antonybudianto/cra-universal#26]
I am getting some error when using react router. 

events.js:182
      throw er; // Unhandled 'error' event
      ^
Invariant Violation: Browser history needs a DOM

So, I think react-router will not work with cra-universal??!!

**Comment by antonybudianto** [comment]
https://github.com/antonybudianto/cra-universal/wiki/Integrate-React-Router

**Comment by knsakib** [comment]
Yes, it works perfectly. :)
