### ISSUE TITLE
Load static files in Server Side Rendering

### ISSUE THREAD

**Issue by rigobertoGomez** [antonybudianto/cra-universal#27]
How can load statics files like a logo of example in create-react-app?
beacuse I have this problem when try to load it!

Warning: Prop src did not match. Server: "[object Object]" Client: "/static/media/logo.5d5d9eef.svg"

**Comment by antonybudianto** [comment]
I think this issue is duplicate with https://github.com/antonybudianto/cra-universal/issues/12

In short, the starter doesn't support svg import at this moment. I think you can still refer the svg file as static, instead of importing them like `import svg from '../icon.svg'`
