### ISSUE TITLE
code-splitting?

### ISSUE THREAD

**Issue by valorloff** [antonybudianto/cra-universal#28]
Hi!
Thanks for your moving in right direction!
point me please the code-split place in the code.
As I understand, there should be sync server rendering and async rendering on client with dynamic bundles added from server, right? 
and sorry, but i don't see where is server-side rendering in sample app (templates/src), just opening index.html file with empty `<div id="root"></div>`

**Comment by antonybudianto** [comment]
of course you will see empty '<div id="root"></div>' since index.html is not the one served to client, but the generated one from server 😄 

As for code-splitting example, you can check out https://github.com/antonybudianto/antonybudianto-web/blob/master/server/src/app.js
