### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by valorloff** [antonybudianto/cra-universal#29]
After:
```
cd ./my-working-create-react-app
cra-universal init
cd ./server
yarn install
yarn start
```
I get:
```
................
[nodemon] starting `node build/bundle.js`
/home/valorloff/my-app/server/build/bundle.js:39966
var isLocalhost = Boolean(window.location.hostname === 'localhost' ||
                          ^
ReferenceError: window is not defined
    at Object.<anonymous> (/home/valorloff/my-app/server/build/bundle.js:39966:27)
```
Can you help?

**Comment by antonybudianto** [comment]
You cannot do DOM checks on server-side, like accessing window, document.

You can only do that on client side code which didn't get executed by server (ex. componentDidMount)

**Comment by valorloff** [comment]
What is entry point of server part? May be need some serverApp?
can you show working example of your package?

**Comment by mparker11** [comment]
@antonybudianto Sorry to bother you but there is something I'm trying to fundamentally understand about SSR. Have you run across times where your bundle.js grabbed third party libraries with the `window` object in it? 

As I see the code in `bundle.js`, I'm not even sure what is being bundled. Is there a way to simply ignore undefined objects, maybe through webpack?

**Comment by antonybudianto** [comment]
@mparker11 , it's a bit tricky if your 3rd party lib doesn't support SSR/isomorphic, but you can still use them on lifecycles that didn't get called during SSR, like `componentDidMount`.

**Comment by mparker11** [comment]
Thanks for the reply. I'll continue trying to figure out which libraries are affecting it. Have you had experience porting over a mature project to use SSR?

**Comment by antonybudianto** [comment]
@mparker11 I hadn't unfortunately

**Comment by MindfulMe** [comment]
In my case, I had mapbox lib, but to be honest I don't need it to be SSR since Googlebot does not care about parsing that kind of map
