### ISSUE TITLE
Add dotenv to server template

### ISSUE THREAD

**Issue by antonybudianto** [antonybudianto/cra-universal#3]
- Add dotenv to server template
- add .env.example file

https://github.com/antonybudianto/cra-universal/tree/master/templates/server

**Comment by nidble** [comment]
Can I work on this?

**Comment by antonybudianto** [comment]
sure!

**Comment by nidble** [comment]
I'm ready for the pull request. But after one questions:
-  I add .env.example into: templates/server/.env.example. Currently this support only PORT info, do you prefer other env variables, ie: NODE_ENV ?

**Comment by antonybudianto** [comment]
I think PORT is good enough, but I'm okay with NODE_ENV too, thanks!
