### ISSUE TITLE
what should be done in case of rendering a img src

### ISSUE THREAD

**Issue by knsakib** [antonybudianto/cra-universal#30]
if I use an img scr (.png) in react app (import style) it is throwing error in rendering server side. react app is showing fine

**Comment by antonybudianto** [comment]
https://github.com/antonybudianto/cra-universal/issues/16

Let me know if it helps

**Comment by knsakib** [comment]
Yes it worked. :)
However, I didn't add all that exclude rule. It is possible just by changing the following line in webpack.config.js. I Changed 

test: /\.(css|svg)?$/,
TO
test: /\.(css|svg|png)?$/,

Working perfect for me. For JPG and other, just by adding those extension should work. 

Thanks for the help. :)

**Comment by antonybudianto** [comment]
Glad it worked :+1: 

By the way, do you mind sharing the project you're working on that used this CLI? Project name and logo would be nice, I'm planning to put it on README.md.

**Comment by knsakib** [comment]
yes, sure. It is not a large site. I am just using it in my personal site and testing for now, which I will use later to make a good project. 
https://knsakib.com
