### ISSUE TITLE
cra-universal build fails on windows

### ISSUE THREAD

**Issue by ShaneMckenna23** [antonybudianto/cra-universal#32]
This could be just an issue with my machine. The build.js wouldn't run npm.

`spawnSync('npm', ['run', 'build'] -> spawnSync('npm.cmd', ['run', 'build'] `

https://github.com/nodejs/node/issues/3675

**Comment by antonybudianto** [comment]
Yes, I've got some reports on this too, but can't really debug since I don't have windows machine.

Do you know the fix? @ShaneMckenna23

**Comment by antonybudianto** [comment]
can you open the pull request? I'll take a look and merge it, then release the patch 😄
