### ISSUE TITLE
Static/css files serve

### ISSUE THREAD

**Issue by VitaliyGaliy** [antonybudianto/cra-universal#36]
Thanks for answer! Have a few more questions -

1. In development mode with ssr, how can I serve static files (images)? For example I heve ones in my project folder.
2. When I try to put a style.css file inside public directory and in index.html show - I get those css-file in browser but it has a wrong type - html, not css.

**Comment by antonybudianto** [comment]
1. Please check https://github.com/antonybudianto/cra-universal/issues/30
2. I don't get this one, any reproduction repo will be great

**Comment by antonybudianto** [comment]
Closing as no reply, will reopen as needed
