### ISSUE TITLE
create-react-app 2.0.0 support

### ISSUE THREAD

**Issue by patroza** [antonybudianto/cra-universal#44]
Hi,

What's the plan/roadmap on 2.0.0 support?
I seem to have it working to a large extent with cra-universal, but am missing some clues with regard to css modules support which was added to 2.0, and also getting blanks for svg's (img src `[Object object]`).

Thanks

Ref: https://github.com/facebook/create-react-app/issues/3815

**Comment by antonybudianto** [comment]
hi,

for svg import, it's on https://github.com/antonybudianto/cra-universal/wiki/Known-issues

**Comment by antonybudianto** [comment]
may I know the css module issue?

**Comment by antonybudianto** [comment]
the library itself should provide SSR support, just like React helmet, react router, loadable component, etc.

**Comment by antonybudianto** [comment]
also `correct synchronization between the 'randomized' class names ` is one similar issue with svg import 😢

**Comment by antonybudianto** [comment]
@patroza Have you tried modules.css loader? Any reproducible will be helpful here

**Comment by geminiyellow** [comment]
? this library only support cra v1.x ?

**Comment by antonybudianto** [comment]
I've not used 2.0.0 since it's not released yet, please open new issue for any incompatibilities :)
