### ISSUE TITLE
Improve cra-universal.now.sh demo page

### ISSUE THREAD

**Issue by antonybudianto** [antonybudianto/cra-universal#5]
The code lives on `./docs`
- Landing page to promote CRA universal CLI

**Comment by stereobooster** [comment]
view-source:https://cra-universal.now.sh/

doesn't contain pre rendered content

**Comment by antonybudianto** [comment]
Using chrome view page source will only show the cached service worker version. You may test using curl

**Comment by stereobooster** [comment]
You can take https://github.com/stereobooster/an-almost-static-stack as an example project. I'm using it to demo react-snap. But I got into one small problem: prerendering and code split doesn't do good friends - at some point loading of async component [triggers redraw](https://github.com/stereobooster/an-almost-static-stack/blob/react-snap/images/visual-progress.png). Do you getting this problem?

Sidenote: did you see [razzle](https://github.com/jaredpalmer/razzle)? It also uses approach of two webpack configs.

**Comment by antonybudianto** [comment]
> at some point loading of async component triggers redraw.
For redraw, did you mean redraw warning on development (element mismatch between client and server render)? If it's, then I don't get this problem.

> You can take https://github.com/stereobooster/an-almost-static-stack as an example project
Nice repo, so we can actually hook into react-scripts package, will investigate further

**Comment by stereobooster** [comment]
No I mean visually

![](https://raw.githubusercontent.com/stereobooster/an-almost-static-stack/react-snap/images/visual-progress.png)

graph from https://webpagetest.org

**Comment by antonybudianto** [comment]
![fireshot capture 2 - webpagetest - visual compariso_ - https___www webpagetest org_video_compare php](https://user-images.githubusercontent.com/7658554/32989345-e1131dd2-cd46-11e7-8c21-dc4620417f90.png)

**Comment by antonybudianto** [comment]
![2](https://user-images.githubusercontent.com/7658554/32989440-807eceb0-cd48-11e7-82f2-f971d035591c.png)

blue (latest cra, with loadable-components + nodestream)
red (old cra, with react-loadable + nodestream)

**Comment by stereobooster** [comment]
I see. I want to implement something more complex rather than pure state. Maybe fetch request. What would you prefer for this? `redux-thunk`?

**Comment by antonybudianto** [comment]
I'm using `redux-thunk`, it's great and simple

**Comment by rigobertoGomez** [comment]
I have this problem, exist a solution? 

Connected to CRA Client dev server
CRA Server listening on port 3001!
connect ECONNREFUSED 127.0.0.1:3000

**Comment by VitaliyGaliy** [comment]
Hello. How can I fetch and preload data on server? For example I have componentDidMount method on client, so I need load those data on server...

**Comment by antonybudianto** [comment]
@VitaliyGaliy we don't have that feature as of now

**Comment by VitaliyGaliy** [comment]
Thanks for answer! Have a few more questions -
1. In development mode with ssr, how can I serve static files (images)? For example I heve ones in my project folder. 
2. When I try to put a style.css file inside public directory and in index.html show - <link href="assets/css/style.css" rel="stylesheet" type="text/css"/> I get those css-file in browser but it has a wrong type - html, not css.

**Comment by antonybudianto** [comment]
@VitaliyGaliy please create new issue
