### ISSUE TITLE
[Object object] appears momentarily

### ISSUE THREAD

**Issue by zamirkhan** [antonybudianto/cra-universal#50]
I've nearly got cra-universal working the way I need. Basically everything works as I expect. However, when I navigate to a server-side rendered page, it will show [Object object] briefly (for about 1 second or less, but noticeable) and then the actual styled React page will render. This happens both in dev and production. I'm not sure what is causing this or how I can avoid it.

**Comment by antonybudianto** [comment]
Hi,

Where `[Object object] briefly` showing on?
Screenshot or simple repo will be better

**Comment by antonybudianto** [comment]
Probably
https://en.wikipedia.org/wiki/Flash_of_unstyled_content

**Comment by zamirkhan** [comment]
Boiling it down to a simple repro scenario would be best, but something I unfortunately don't have time for right now. The app itself is fairly large, but I can e-mail you a link if you like.

What I see is that in the server/app.js I'm using

```
const app = createReactAppExpress({
  clientBuildPath,
  handleRender: stringRenderer,
  universalRender: handleUniversalRender,
  async onFinish(req, res, html) {
...
```

I think it's the stringRenderer that gets invoked. In the onFinish method, there is already:

```
...
<div id="root">[Object object]</div>
...

```

For now, as a workaround, I simply remove that undesirable part of the string.

**Comment by antonybudianto** [comment]
Hmm it's weird though, it's like something non-React element is being passed to https://reactjs.org/docs/react-dom-server.html#rendertostring

can you share `handleUniversalRender` snippet?

**Comment by zamirkhan** [comment]
Sure:

```
function handleUniversalRender(req, res) {
  context = {};

  const stream = ReactDOMServer.renderToNodeStream(
    <StaticRouter location={req.url} context={context}>
      <App />
    </StaticRouter>
  );

  if (context.url) {
    res.redirect(301, context.url);
    return;
  }

  return stream;
}

```

**Comment by antonybudianto** [comment]
@zamirkhan I see, so if you choose stream renderer, then onFinish is currently not supported, 
https://github.com/antonybudianto/create-react-app-express/blob/master/packages/universal-loader/src/renderer/stream-renderer.js

also you can remove  `handleRender: stringRenderer,` since you're using node stream in `handleUniversalRender`

**Comment by antonybudianto** [comment]
unfortunately, there's no way for setting meta tags using node-stream api, since the headers already being sent on stream.. you can stick to string renderer if you need meta tags replace

**Comment by zamirkhan** [comment]
I'll keep the current implementation. It works, that's the most important part. Thank you for building such a useful tool and for looking into this with me.

**Comment by antonybudianto** [comment]
You're welcome 👍

**Comment by antonybudianto** [comment]
If you use react helmet and node streaming, this might help
https://github.com/nfl/react-helmet/issues/322

**Comment by heshamelmasry77** [comment]
@zamirkhan  Hello could you please write to me how did you remove it. the hack you said you wrote.
It will really help :) 

i did that :
 in the ```  index.html  ```
 ```
<script type ="text/javascript">

              document.getElementById('root').innerHTML = '';
      </script>

```
but it is not working

**Comment by heshamelmasry77** [comment]
i remoe the window.onload 
```
-window.onload = () => {
-  Loadable.preloadReady().then(() => {
-    ReactDOM.hydrate(
-      <BrowserRouter>
-        <App />
-      </BrowserRouter>,
-      document.getElementById('root')
-    );
-  });
-};
```
```
+Loadable.preloadReady().then(() => {
+  ReactDOM.hydrate(
+    <BrowserRouter>
+      <App />
+    </BrowserRouter>,
+    document.getElementById('root')
+  );
+});
```

**Comment by zamirkhan** [comment]
@heshamelmasry77 the removal is done server side. I do it in the onFinish handler: 

`async onFinish(req, res, html) {
    if (context.status === 404) {
      return res.status(404).send(html);
    }
    if (context.url) {
      return res.redirect(301, context.url);
    }

    
    var finalHtml = html;

    const $ = cheerio.load(html);

    $('#root').empty();

     ...`

You don't need to use `cheerio` (I used it for a bunch of other manipulations), but you get the idea.
