### ISSUE TITLE
Using https with localhost

### ISSUE THREAD

**Issue by joelaguero** [antonybudianto/cra-universal#77]
I'm attempting to use https in my dev environment, however the [the "best practice"](https://medium.freecodecamp.org/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec) I found currently requires passing in certOptions (see below):
```
var path = require('path')
var fs = require('fs')
var express = require('express')
var https = require('https')

var certOptions = {
  key: fs.readFileSync(path.resolve('build/cert/server.key')),
  cert: fs.readFileSync(path.resolve('build/cert/server.crt'))
}

var app = express()

var server = https.createServer(certOptions, app).listen(443)
```
Is it possible to achieve this functionality with `cra-universal`? Or enable https for localhost support?

**Comment by antonybudianto** [comment]
Hi,

I've never tried this before, can you try it on this file? I assume you've the same file on your app
https://github.com/antonybudianto/antonybudianto-web/blob/master/server/index.js

**Comment by antonybudianto** [comment]
I'll investigate it during my free time

**Comment by antonybudianto** [comment]
@joelaguero , Hi, is it working on your side?

**Comment by joelaguero** [comment]
@antonybudianto I haven't had a chance to dig deeper and actually migrated to a different boilerplate for other reasons, so probably won't be able to solve this in the near term. Thanks for your work on `cra-universal` though, it was just what I needed to get going.

**Comment by Dashue** [comment]
@antonybudianto I'm interested to hear if setting https=true like with regular CRA works?
See this: https://github.com/facebook/create-react-app/blob/0febe269b555d922f7726f30d505ed5cca2598ec/docusaurus/docs/using-https-in-development.md

**Comment by antonybudianto** [comment]
@Dashue not yet, I'm open for the PR

**Comment by antonybudianto** [comment]
never done that before 😅 , maybe you can follow @joelaguero's snippet

**Comment by Dashue** [comment]
Was pretty easy.
Because createReactAppExpress returns expressApp I just had to change my index.js to this.

`require('dotenv').config();
const expressApp = require('./app').default;
var https = require('https');
var fsSync = require('fs');

const PORT = process.env.PORT || 3000;

var certOptions = { key: '', cert: '', ca: '', passphrase: '' };
if (process.env.NODE_ENV === 'development') {
  certOptions = {
    key: fsSync.readFileSync('./<redacted>.key', 'utf8'),
    cert: fsSync.readFileSync('./<redacted>.crt', 'utf8'),
    ca: fsSync.readFileSync('./<redacted>.crt', 'utf8'),
    passphrase: '<redacted>'
  };
}

https.createServer(certOptions, expressApp)
  .listen(PORT, () => {
    console.log(`CRA Server listening on port ${PORT}!`);
  });`
