### ISSUE TITLE
npx cra-universal start doesn't get executed

### ISSUE THREAD

**Issue by scaledrop** [antonybudianto/cra-universal#78]
I end up with the following logs.
```
sswp> Script loaded
connect ECONNREFUSED 127.0.0.1:3000
```
It is starting neither on port 3000 nor 3001. Please suggest.

**Comment by antonybudianto** [comment]
You need to start your CRA client:
```
npm start
npx cra-universal start
```

sorry it's not being clear

**Comment by antonybudianto** [comment]
or you can do `npx cra-universal start --both` so that it'll start both client and server

**Comment by scaledrop** [comment]
Yeah thanks. I started both client as well as server and it started working.
Now next thing comes is production build. The steps you've given very tedious. Can you just merge it into one simple command.
And last one is, routing. My question to you is, does it have inbuilt universal routing too? If i just integrate react-router-dom with switch, route etc. Will it work universally? like below
```
<Switch>
          {routes.map(({ path, exact, component: Component}) => (
            <Route
              key={path}
              path={path}
              exact={exact}
              render={props => <Component {...props} />}
            />
          ))}
          <Route render={props => <NoMatch {...props} />} />
        </Switch>
```

**Comment by antonybudianto** [comment]
Can you please explain what do you mean by `The steps you've given very tedious` ? You can also send a PR if you want, if it's good, I may merge. For now, I don't plan to change it.

No, I don't assume any routing solution because I don't want to make it opinionated. 
If you use react-router, you can check https://github.com/antonybudianto/cra-universal/wiki/Integrate-React-Router

**Comment by scaledrop** [comment]
The following process we've to take to run the production build. You could make it something ie - `npx cra-universal start:ssr` It would much easier to get the production app ready.

# Production
 Change directory to your project root first, and run:
npx cra-universal build

This command will build both client and server and put them into `./dist`
# Deployment
First, follow the Production guide mentioned above.
Since the bundle used Webpack Node Externals, you need to run npm install --production on the copied /dist, but this time you don't need to install its devDependencies
Use process manager like PM2 to run your server, your run target is ./dist/server/bundle.js

**Comment by antonybudianto** [comment]
Sorry since it's far too opinionated, I cannot make it into the core CLI. Each dev have their own production/deployment pipeline, my CLI scope is only up to generating the server bundle.
But you can always fork and add them :)

**Comment by scaledrop** [comment]
cool!
