### ISSUE TITLE
Problem with Router

### ISSUE THREAD

**Issue by hoantran-it** [antonybudianto/cra-universal#89]
When I start cra-universal, I face up an error like this: **Module not found: Error: Can't resolve 'Router'**

My project look like this:

`ReactDOM.hydrate(<App />, document.getElementById("root"));`

```
const App = () => (
  <Provider store={store.store}>
    <PersistGate loading={<div>Loading...</div>} persistor={store.persistor}>
      <LanguageProvider messages={translationMessages}>
        <MuiThemeProvider>
          <Router/>
        </MuiThemeProvider>
      </LanguageProvider>
    </PersistGate>
  </Provider>
);
```
Do I need to tweak something in my code before apply cra-universal. Please give me advice. Thanks!

**Comment by antonybudianto** [comment]
Hi,

Please check here:
 https://github.com/antonybudianto/cra-universal/wiki/Integrate-React-Router

Hope it helps

**Comment by antonybudianto** [comment]
Also https://github.com/antonybudianto/antonybudianto-web/blob/master/server/app.js#L34

**Comment by hoantran-it** [comment]
Sorry, I have a question that where **server/src/app.js** file is? I just only follow the Installation guideline and I do not have any file like this. Am I missing something?

**Comment by antonybudianto** [comment]
From v3.0.0, you can run `npx cra-universal init` to generate `server` folder

**Comment by antonybudianto** [comment]
https://antonybudianto.github.io/cra-universal/docs/cra-universal-cli.html#init

**Comment by antonybudianto** [comment]
I've not tested on React 15 yet, but I encourage all user to upgrade to React 16 (17 is near too)

For v3.0.0, by default it will use Node stream rendering, which requires API from React 16. You can use string renderer instead.
https://github.com/antonybudianto/antonybudianto-web/blob/master/server/app.js#L17

For upcoming v4, the default will be String renderer.
