### ISSUE TITLE
title is rendering only react App

### ISSUE THREAD

**Issue by gmchaturvedi1** [antonybudianto/cra-universal#9]
Dear friends,

thanks for the good work.

i have added react-helmet in my create react app but when i check on build the header is always coming react app even when i render  my website through facebook and twitter. can u suggest me what to do for server side so tile and other meta information show as defined in react-helmet.

Regards
gmchaturvedi

**Comment by antonybudianto** [comment]
This might help
https://github.com/nfl/react-helmet#server-usage

**Comment by antonybudianto** [comment]
But looks like React 16 SSR support is still on their issues
https://github.com/nfl/react-helmet/issues/322

**Comment by gmchaturvedi1** [comment]
shall we use react-head  with cra-universal ?

**Comment by antonybudianto** [comment]
not sure, from the documentation, they only use renderToString API.

**Comment by gmchaturvedi1** [comment]
any thing suggest so we can use SEO friendly tags.

**Comment by antonybudianto** [comment]
sorry for now I've no other suggestions, I'm still investigating it though
