### ISSUE TITLE
Do we support NODE_PATH in server

### ISSUE THREAD

**Issue by hoantran-it** [antonybudianto/cra-universal#92]
When I use CRA, I defined **NODE_PATH=src/** in **.env** file. It help me a lot on import. For example: 

**import Item from "components/item/Item"**

When I start cra-universal, NODE_PATH is not apply, I have to tweak something like this  to make it work.

**import Item from "../../components/item/Item"**

Any suggestion on it. Thanks!

**Comment by antonybudianto** [comment]
I think you can use https://webpack.js.org/configuration/resolve/#resolve-modules

**Comment by hoantran-it** [comment]
I tried, but no luck

`
module.exports = {
  app,
  resolve: {
    modules: ['src/', 'node_modules']
  }
};
`
`
module.exports = {
  app,
  resolve: {
    modules: ['../src/', 'node_modules']
  }
};
`
`
module.exports = {
  app,
  resolve: {
    modules: ['./src/', 'node_modules']
  }
};
`

**Comment by hoantran-it** [comment]
I think it nice to have the feature support to custom some specific webpack config instead of overriding all.

**Comment by antonybudianto** [comment]
I think I'll add NODE_PATH to modules entry internally, but it'll be shipped on v4

**Comment by antonybudianto** [comment]
also I think NODE_PATH usage is discouraged  https://github.com/webpack/webpack/issues/4479#issuecomment-286701441

**Comment by hoantran-it** [comment]
Thank you @antonybudianto !
