### ISSUE TITLE
Support arrow function

### ISSUE THREAD

**Issue by hoantran-it** [antonybudianto/cra-universal#97]
Default webpack config does not support arrow function of ES6. Do you intend to fix it or open for PR?

**Comment by antonybudianto** [comment]
I'm open for PR :)

**Comment by antonybudianto** [comment]
You meant arrow function is not working on crau.config.js right?

**Comment by antonybudianto** [comment]
Also which Node version you're using?

**Comment by antonybudianto** [comment]
Ah I see, that's not arrow function issue, but class properties proposal
https://babeljs.io/docs/en/babel-plugin-transform-class-properties

Since it's still on proposal stage, I'm not including it, you can add it to your `server/.babelrc`

**Comment by hoantran-it** [comment]
Ok I got it. Thank you very much!

**Comment by hoantran-it** [comment]
I tried with your suggestion and got an error.
![image](https://user-images.githubusercontent.com/13161875/45919504-8342ee00-bec0-11e8-80bb-11f12eaf7c3e.png)

Could you please to help me? Thanks! @antonybudianto

**Comment by antonybudianto** [comment]
Since you're overriding `.babelrc`, you need to include the default:
```json
{
  "presets": ["env", "react"],
  "plugins": [
    "dynamic-import-node",
    "transform-object-rest-spread",
    "transform-class-properties"
  ]
}
```

**Comment by hoantran-it** [comment]
Thanks for explanation! What a enthusiastic guru!
