### ISSUE TITLE
Loop with creating build

### ISSUE THREAD

**Issue by Yuricoden** [antonybudianto/cra-universal#98]
When creating a build(my process have hard temperature) I have a cycle, what to do in this case? 

![2018-09-21 21 35 52](https://user-images.githubusercontent.com/19597527/45899915-e1030780-bde6-11e8-8b5a-8dd73cb2da5b.png)

**Comment by antonybudianto** [comment]
Is this related with https://github.com/antonybudianto/cra-universal/issues/93 ?

**Comment by antonybudianto** [comment]
Also make sure:
- You run your build with `npx cra-universal build`
- The build script in your package.json is `react-scripts build`, **not** cra-universal build

**Comment by Yuricoden** [comment]
I'm using the v3.2.5 build of the cra-universal.

> Is this related with #93 ?
> 
> Please let me know which cra-universal version you use

**Comment by antonybudianto** [comment]
Please provide any reproducible repo, I can't reproduce this case with current build

**Comment by Yuricoden** [comment]
As soon as I cleared my project and left only one router and one file all work. But my real project is big.

**Comment by Yuricoden** [comment]
I think if the project is big then it freezes

**Comment by Yuricoden** [comment]
Could the reason be that I do not use redux.

**Comment by Yuricoden** [comment]
![2018-09-22 17 32 19](https://user-images.githubusercontent.com/19597527/45918303-8cff2e00-be8d-11e8-978a-950207ffcef7.png)
one routes

many routes

![2018-09-22 17 34 07](https://user-images.githubusercontent.com/19597527/45918316-c9cb2500-be8d-11e8-8036-bcee0a8e2002.png)

**Comment by antonybudianto** [comment]
Not sure, maybe there's something wrong with the library you used, not particularly cra-universal issue. I don't think I can help much since I cannot reproduce at all.

**Comment by Yuricoden** [comment]
The assembly of the client is going all fine.

The problem with the hangup in the second step when building the server.

**Comment by Yuricoden** [comment]
Yeah!! my problem is solved by this command:
node --max_old_space_size=8000 $(which npx) cra-universal build
