### ISSUE TITLE
Props not rendering in (view:source)

### ISSUE THREAD

**Issue by Yuricoden** [antonybudianto/cra-universal#99]
In my application on the localhost server: 3001. cra-universal do not render my data that I get from the server. I need to fix this for SEO.

![2018-09-23 02 01 22](https://user-images.githubusercontent.com/19597527/45922451-040be500-bed5-11e8-826a-461acaa490c5.png)

![2018-09-23 02 08 55](https://user-images.githubusercontent.com/19597527/45922486-afb53500-bed5-11e8-863a-6b38d9e7fa68.png)

**Comment by antonybudianto** [comment]
You might take a look at https://github.com/antonybudianto/cra-universal/tree/master/packages/%40cra-express/redux-prefetcher

**Comment by antonybudianto** [comment]
The demo https://github.com/antonybudianto/cra-universal/tree/master/packages/demo

**Comment by Yuricoden** [comment]
I do not use the redux what to do in this case?

**Comment by antonybudianto** [comment]
Right now I only have solution for redux + react-router, I'm open for PR if you have any unopinionated solution

**Comment by antonybudianto** [comment]
I found https://github.com/jaredpalmer/react-router-nextjs-like-data-fetching, I think this is good, not using Redux

**Comment by antonybudianto** [comment]
Right now I'm developing the new router-prefetcher https://github.com/antonybudianto/cra-universal/tree/new-router-prefetcher, but will release much later...

For now you can follow Jared's repo, I've tried and it works well.

**Comment by Yuricoden** [comment]
For this demonstration there is no need to install the framework razzle? I did not really understand how to use it in my project. Maybe your have example for this plugin?

**Comment by Yuricoden** [comment]
I'll use the react without the redux and I'll be very grateful for the example)

**Comment by antonybudianto** [comment]
The example is within https://github.com/antonybudianto/cra-universal/tree/new-router-prefetcher branch, you can check the `packages/demo`
